function [fitresult, gof, yy] = createFit3(x, fixedUpLine)
%CREATEFIT1(X,FIXEDUPLINE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: fixedUpLine
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Jun-2014 19:24:52


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, fixedUpLine );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( ft );
opts.SmoothingParam = 0.01;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
yy = fitresult(x);
% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% plot( fitresult, xData, yData );
% % Label axes
% xlabel( 'x' );
% ylabel( 'fixedUpLine' );
% grid on


