function [XDEN,cfsDEN,dimCFS] = func_denoise_dw2d(X)
% FUNC_DENOISE_DW2D Saved Denoising Process.
%   X: matrix of data
%   -----------------
%   XDEN: matrix of denoised data
%   cfsDEN: decomposition vector (see WAVEDEC2)
%   dimCFS: corresponding bookkeeping matrix

%  Auto-generated by Wavelet Toolbox on 21-Jun-2014 19:00:07

% Analysis parameters.
%---------------------
wname = 'sym4';
level = 4;

% Denoising parameters.
%-----------------------
% meth = 'sqtwolog';
% scal_OR_alfa = one;
sorh = 's';    % Specified soft or hard thresholding
thrSettings =  [...
    4.855789193353290      4.569402090104097      4.274011848021932      3.971418235788254 ; ...
    4.855789193353290      4.569402090104097      4.273627570237765      3.971418235788254 ; ...
    4.855789193353290      4.569402090104097      4.273627570237765      3.971418235788254   ...
    ];
roundFLAG = true;

% Denoise using WDENCMP.
%----------------------
[coefs,sizes] = wavedec2(X,level,wname);
[XDEN,cfsDEN,dimCFS] = wdencmp('lvd',coefs,sizes, ...
    wname,level,thrSettings,sorh);
if roundFLAG , XDEN = round(XDEN); end
if isequal(class(X),'uint8') , XDEN = uint8(XDEN); end
